apiVersion: v1
# PersistentVolumeClaim: persistent volumes types available for the pods.
kind: PersistentVolumeClaim
metadata:
   name: database-persistent-volume-claim
spec:
   # accessModes:
   # 1. ReadWriteOnce: can be used by a single node at a time for read/write.
   # 2. ReadOnlyMany: multiple nodes at the same time can read.
   # 3. ReadWriteMany: multiple nodes at the same time can read/write.
   accessModes:
      - ReadWriteOnce
   resources:
      requests:
         storage: 2Gi
